modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="mip"
version="1.0.0"
displayName="rp_mip_mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Lexxx, MCreator"

[[dependencies.mip]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




